# Generated by Django 3.2.22 on 2023-10-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Название места')),
                ('description_short', models.CharField(max_length=200, verbose_name='Описание места - кратко')),
                ('description_long', models.TextField(verbose_name='Подробное описание места')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('lat', models.FloatField(verbose_name='широта')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
