# Generated by Django 3.2.22 on 2023-10-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='description_short',
            field=models.CharField(max_length=400, verbose_name='Описание места - кратко'),
        ),
    ]
