# Generated by Django 4.2.7 on 2024-02-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(default='Локация', max_length=100, null=True, unique=True, verbose_name='Название места'),
        ),
    ]
