# Generated by Django 4.2.7 on 2024-02-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, verbose_name='Описание места - кратко'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(default='Локация', max_length=100, unique=True, verbose_name='Название места'),
        ),
    ]
