# Generated by Django 3.2.22 on 2023-10-31 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_places_description_short'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
