# Generated by Django 3.2.22 on 2023-11-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_places_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=100, null=True, verbose_name='Название места')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='imgs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.pictures', verbose_name='картинки'),
        ),
    ]
