# Generated by Django 4.2.7 on 2024-02-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_description_short_alter_place_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_order',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='Порядок сортировки'),
        ),
    ]
