# Generated by Django 4.2.7 on 2024-02-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_place_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='unique_location',
            new_name='slug',
        ),
    ]
