# Generated by Django 3.2.22 on 2023-11-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20231101_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.RemoveField(
            model_name='place',
            name='imgs',
        ),
        migrations.AddField(
            model_name='place',
            name='imgs',
            field=models.ManyToManyField(blank=True, null=True, to='places.Pictures', verbose_name='картинки'),
        ),
    ]
