# Generated by Django 4.2.7 on 2024-02-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pic_order',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='Порядок сортировки'),
        ),
    ]
