# Generated by Django 3.2.22 on 2023-11-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20231123_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='imgs',
        ),
        migrations.AddField(
            model_name='place',
            name='pictures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.pictures', verbose_name='картинки'),
        ),
        migrations.AddField(
            model_name='place',
            name='placeID',
            field=models.SlugField(blank=True, default='', max_length=150, unique=True, verbose_name='ID места'),
        ),
    ]
