# Generated by Django 3.2.22 on 2023-11-24 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_placeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='pictures',
        ),
        migrations.AddField(
            model_name='pictures',
            name='place',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='places.place', verbose_name='Место'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(upload_to='place_pic', verbose_name='Картинки'),
        ),
    ]
