# Generated by Django 3.2.22 on 2023-11-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20231124_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='placeID',
            field=models.SlugField(blank=True, default='', max_length=150, unique=True, verbose_name='ID места'),
        ),
    ]
