# Generated by Django 3.2.22 on 2023-11-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_place_placeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='placeID',
            field=models.CharField(blank=True, default='', max_length=32, unique=True, verbose_name='ID места'),
        ),
    ]
