# Generated by Django 3.2.22 on 2023-11-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_place_placeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='placeID',
        ),
    ]
