# Generated by Django 3.2.22 on 2023-11-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_remove_place_placeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeID',
            field=models.SlugField(blank=True, default='', max_length=150, verbose_name='ID места'),
        ),
    ]
