# Generated by Django 4.2.7 on 2023-11-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_place_placeid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictures',
            options={'ordering': ['pic_order'], 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AddField(
            model_name='pictures',
            name='pic_order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
