# Generated by Django 4.2.7 on 2023-11-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_pictures_options_pictures_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='pic_order',
            field=models.SmallIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
