# Generated by Django 4.2.7 on 2023-11-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_pictures_pic_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='pic_order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
