# Generated by Django 4.2.7 on 2023-11-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_alter_pictures_pic_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['place_order'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AddField(
            model_name='place',
            name='place_order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
